name: Golnag CI
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GIT_USER:
        required: true
      GIT_TOKEN:
        required: true
    outputs:
      image:
        description: 'The image of docker build tag'
        value: ${{ jobs.buildAndPush.outputs.deployment_key_for_api_encrypted }}
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ inputs.version }}
      LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
    outputs:
      deployment_key_for_api_encrypted: ${{ steps.set_outputs.outputs.deployment_key_for_api_encrypted }}
      deployment_key_for_client_encrypted: ${{ steps.set_outputs.outputs.deployment_key_for_client_encrypted }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache tets
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: set GOPRIVATE
        run: |
            go env -w GOPRIVATE=github.com/ohdat
            git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: 1.7.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }},${{ env.LATEST_TAG }}

      - name: Set outputs
        id: set_outputs
        shell: bash
        run: |
          deployment_key_for_api="Method of obtaining this has been removed for simplicity..."
          echo "::add-mask::$deployment_key_for_api"
          deployment_key_for_api_encrypted=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$deployment_key_for_api") | base64 -w0)
          echo "::set-output name=deployment_key_for_api_encrypted::$deployment_key_for_api_encrypted"

          deployment_key_for_client="Method of obtaining this has been removed for simplicity..."
          echo "::add-mask::$deployment_key_for_client"
          deployment_key_for_client_encrypted=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$deployment_key_for_client") | base64 -w0)
          echo "::set-output name=deployment_key_for_client_encrypted::$deployment_key_for_client_encrypted"
        env:
          SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
