name: Helm CD
on:
  workflow_call:
    inputs:
      commond:
        required: true
        type: string
    secrets:
      kubename:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: update kubeconfig
        run:   aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.kubename }}
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: update helm repo
        run: |
          helm repo add ohdat https://ohdat.github.io/helm-charts/
          helm repo update
      - name: helm deploy
        run:  helm upgrade -i ${{ inputs.commond }} 